"""Initial schema: contacts, relationships, tags, notes tables

Revision ID: d0e5116eecf5
Revises: 
Create Date: 2025-08-15 13:44:10.144314

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0e5116eecf5'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('contacts', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('contacts', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               nullable=False)
    op.alter_column('contacts', 'email',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
    op.alter_column('notes', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('notes', 'title',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
    op.add_column('people', sa.Column('raw_data', sa.Text(), nullable=True))
    op.add_column('people', sa.Column('created_at', sa.DateTime(), nullable=True))
    op.add_column('people', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.alter_column('people', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.drop_column('people', 'relationshipInterests')
    op.drop_column('people', 'locales')
    op.drop_column('people', 'occupations')
    op.drop_column('people', 'etag')
    op.drop_column('people', 'imClients')
    op.drop_column('people', 'sipAddresses')
    op.drop_column('people', 'relationshipStatuses')
    op.drop_column('people', 'genders')
    op.drop_column('people', 'metadata')
    op.drop_column('people', 'memberships')
    op.drop_column('people', 'addresses')
    op.drop_column('people', 'nicknames')
    op.drop_column('people', 'phoneNumbers')
    op.drop_column('people', 'photos')
    op.drop_column('people', 'urls')
    op.drop_column('people', 'birthdays')
    op.drop_column('people', 'locations')
    op.drop_column('people', 'skills')
    op.drop_column('people', 'externalIds')
    op.drop_column('people', 'resourceName')
    op.drop_column('people', 'braggingRights')
    op.drop_column('people', 'miscKeywords')
    op.drop_column('people', 'fileAses')
    op.drop_column('people', 'ageRanges')
    op.drop_column('people', 'events')
    op.drop_column('people', 'ageRange')
    op.drop_column('people', 'relations')
    op.drop_column('people', 'userDefined')
    op.drop_column('people', 'clientData')
    op.drop_column('people', 'interests')
    op.drop_column('people', 'emailAddresses')
    op.drop_column('people', 'coverPhotos')
    op.drop_column('people', 'organizations')
    op.drop_column('people', 'residences')
    op.drop_column('people', 'calendarUrls')
    op.drop_column('people', 'names')
    op.drop_column('people', 'taglines')
    op.drop_column('people', 'biographies')
    op.alter_column('relationships', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('tags', 'id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
    op.alter_column('tags', 'name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tags', 'name',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('tags', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('relationships', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.add_column('people', sa.Column('biographies', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('taglines', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('names', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('calendarUrls', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('residences', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('organizations', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('coverPhotos', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('emailAddresses', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('interests', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('clientData', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('userDefined', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('relations', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('ageRange', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('events', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('ageRanges', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('fileAses', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('miscKeywords', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('braggingRights', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('resourceName', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('externalIds', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('skills', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('locations', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('birthdays', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('urls', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('photos', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('phoneNumbers', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('nicknames', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('addresses', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('memberships', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('metadata', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('genders', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('relationshipStatuses', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('sipAddresses', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('imClients', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('etag', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('occupations', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('locales', sa.TEXT(), nullable=True))
    op.add_column('people', sa.Column('relationshipInterests', sa.TEXT(), nullable=True))
    op.alter_column('people', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.drop_column('people', 'updated_at')
    op.drop_column('people', 'created_at')
    op.drop_column('people', 'raw_data')
    op.alter_column('notes', 'title',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
    op.alter_column('notes', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    op.alter_column('contacts', 'phone',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'email',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.alter_column('contacts', 'name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               nullable=True)
    op.alter_column('contacts', 'id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)
    # ### end Alembic commands ###
